### ISSUE TITLE
cannot register with hostname to etcd  in docker

### ISSUE THREAD

**Issue by morphyguo** [micro/examples#120]
I ran booking example and the registry is etcd, Here is my docker-compose file.
```
micro:
  hostname: micro
  command:   --registry=etcd --registry_address=etcd:2379 api  --handler=rpc
  image: microhq/micro:latest
  links:
    - etcd
    - api
  ports:
    - "8080:8080"
api:
  build: ./api/hotel
  command: --registry=etcd --registry_address=etcd:2379 
  links:
    - etcd
    - auth
    - geo
    - profile
    - rate
auth:
  build: ./srv/auth
  command: --registry=etcd --registry_address=etcd:2379 
  links:
    - etcd
geo:
  build: ./srv/geo
  command: --registry=etcd --registry_address=etcd:2379
  links:
    - etcd
profile:
  build: ./srv/profile
  command: --registry=etcd --registry_address=etcd:2379
  links:
    - etcd
rate:
  build: ./srv/rate
  command: --registry=etcd --registry_address=etcd:2379
  links:
    - etcd

etcd:
  hostname: etcd
  image: bitnami/etcd:3
#   deploy:
#     replicas: 1
#     restart_policy:
#       condition: on-failure
  ports:
    - "2379:2379"
    - "2380:2380"
    - "4001:4001"
    - "7001:7001"
  user: root
  volumes:
    - "/home/morphy/logs/docker/etcd/data:/opt/bitnami/etcd/data"
  environment:
#    - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
#    - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
#    - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
#    - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
    - "ALLOW_NONE_AUTHENTICATION=yes"
#    - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
#    - "ETCD_NAME=node1"
    - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
```
then
`make build && make run`
and etcdctl can list these services been registered.

However, the services cannot be called by micro api. the error message liked this:
```
curl -H 'Content-Type: application/json'      -H "Authorization: Bearer VALID_TOKEN"            -d '{"inDate": "2015-04-09", "outDate":"2019-01-01"}'             http://localhost:8080/hotel/rates -v| json_pp 

{
   "id" : "go.micro.client.transport",
   "detail" : "malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"",
   "code" : 500,
   "status" : "Internal Server Error"
}
```
Does anyone meet this issue?
